// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcumipsefkuytekaphhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjdW1pcHNlZmt1eXRla2FwaGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Nzk1NTYsImV4cCI6MjA2NjI1NTU1Nn0.Mv0-qBuEg5eLRtrK62_0hdHh279928Sg1wB6HJ_FQHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);